services:
  testapp:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    environment:
      - REQUIRED_SETTING=development
      - DEBUG=True
      - EMAIL_URL=console://
    restart: unless-stopped
networks:
  default:
    name: testapp-network