services:
  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REQUIRED_SETTING=production
      - DEBUG=false
      - EMAIL_URL=console://
      - SECRET_KEY=""
    restart: unless-stopped
    secrets:
       - "django"
       - ".env.secrets"
networks:
  default:
    name: testapp-network
secrets:
   django:
     file: "./secrets/production/secrets.dec.yaml"
   .env.secrets:
     file: "./.env.secrets"