services:
  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REQUIRED_SETTING=production
      - DEBUG=false
      - EMAIL_URL=console://
    restart: unless-stopped
networks:
  default:
    name: testapp-network