services:
  testapp:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    environment:
      - REQUIRED_SETTING=development
      - DEBUG=True
    volumes:
      # Mount source code for development (optional)
      - ./src/testapp:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    restart: unless-stopped

networks:
  default:
    name: testapp-network